language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-stkserver' ]; then cd .. && eval "mv $currentfolder generator-stkserver" && cd generator-stkserver; fi

